version: 1.6.{build}
build_cloud: WIN-LKR467JS4GL
image: Windows
platform:
- x86
- x64
- ARM64
configuration:
- Release
environment:
  UpdaterName: contoso_EmergencyUrl_Updater
test: off
skip_commits:
  files:
    - assets/*
    - '**/*.md'
    - '**/*.json'
    - '**/*.png'
install:
- cmd: git submodule -q update --init
#- cmd: vcpkg integrate install
#- cmd: vcpkg update
# workaround for "CMake Error: Not a file: C:\tools\vcpkg\buildtrees\0.vcpkg_dep_info.cmake"
- ps: Start-Sleep -Seconds (Get-Random -Minimum 1 -Maximum 6)
# manifest mode takes forever to build each commit so use global copy instead
- cmd: vcpkg install argh:%PLATFORM%-windows-static sfml:%PLATFORM%-windows-static imgui[freetype,wchar32]:%PLATFORM%-windows-static imgui-sfml:%PLATFORM%-windows-static restclient-cpp:%PLATFORM%-windows-static nlohmann-json:%PLATFORM%-windows-static magic-enum:%PLATFORM%-windows-static z4kn4fein-semver:%PLATFORM%-windows-static winreg:%PLATFORM%-windows-static hash-library:%PLATFORM%-windows-static spdlog:%PLATFORM%-windows-static scope-guard:%PLATFORM%-windows-static curlpp:%PLATFORM%-windows-static inja:%PLATFORM%-windows-static cpp-httplib:%PLATFORM%-windows-static libzip:%PLATFORM%-windows-static
- ps: Setup-VS2022 $env:PLATFORM
before_build:
- cmd: nuget restore vīcĭus.sln
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\src\vīcĭus.rc" --resource.file-version --resource.product-version
build:
  project: $(APPVEYOR_BUILD_FOLDER)\vīcĭus.sln
after_build:
- cmd: if not %PLATFORM%==arm64 upx -9 -o .\bin\%PLATFORM%\%UpdaterName%_packed.exe .\bin\%PLATFORM%\*.exe
artifacts:
- path: bin\**\*.exe
  name: Updater
- path: bin\**\*.pdb
  name: Symbols
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true
