version: 1.1.{build}
build_cloud: WIN-LKR467JS4GL
image: Windows
platform:
- x86
- x64
- ARM64
configuration:
- Release
environment:
  UpdaterName: contoso_EmergencyUrl_Updater
  SKIP_CA: true
test: off
skip_commits:
  files:
    - assets/*
    - '**/*.md'
    - '**/*.json'
    - '**/*.png'
install:
- cmd: git submodule -q update --init
- cmd: vcpkg integrate install
- cmd: vcpkg update
- ps: Setup-VS2022 $env:PLATFORM
before_build:
- cmd: nuget restore vīcĭus.sln
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\src\vīcĭus.rc" --resource.file-version --resource.product-version
build:
  project: $(APPVEYOR_BUILD_FOLDER)\vīcĭus.sln
after_build:
- cmd: if not %PLATFORM%==arm64 upx -9 -o .\bin\%PLATFORM%\%UpdaterName%_packed.exe .\bin\%PLATFORM%\*.exe
artifacts:
- path: bin\**\*.exe
  name: Updater
- path: bin\**\*.pdb
  name: Symbols
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true
